export const sampleCustomers = [
  {
    name: 'Tech Solutions Inc',
    contactPerson: 'John Smith',
    email: 'john@techsolutions.com',
    phone: '+91-9876543210',
    taxId: 'GSTIN123456789',
    address: '123 MG Road, Bangalore, Karnataka 560001',
    paymentTerms: 30,
  },
  {
    name: 'Global Enterprises Ltd',
    contactPerson: 'Sarah Johnson',
    email: 'sarah@globalent.com',
    phone: '+91-9876543211',
    taxId: 'GSTIN987654321',
    address: '456 Park Street, Mumbai, Maharashtra 400001',
    paymentTerms: 45,
  },
  {
    name: 'Innovative Systems Pvt Ltd',
    contactPerson: 'Raj Kumar',
    email: 'raj@innovativesys.com',
    phone: '+91-9876543212',
    taxId: 'GSTIN456789123',
    address: '789 Commercial Road, Delhi 110001',
    paymentTerms: 30,
  },
  {
    name: 'Digital Marketing Agency',
    contactPerson: 'Priya Sharma',
    email: 'priya@digitalmarket.com',
    phone: '+91-9876543213',
    taxId: 'GSTIN234567890',
    address: '321 Business Park, Pune, Maharashtra 411001',
    paymentTerms: 30,
  },
];

export const sampleVendors = [
  {
    name: 'CloudTech Suppliers',
    contactPerson: 'Michael Brown',
    email: 'michael@cloudtech.com',
    phone: '+91-8765432109',
    gstTin: 'GSTIN111222333',
    paymentTerms: 30,
  },
  {
    name: 'Software Services Inc',
    contactPerson: 'Lisa Anderson',
    email: 'lisa@softwareservices.com',
    phone: '+91-8765432108',
    gstTin: 'GSTIN444555666',
    paymentTerms: 45,
  },
  {
    name: 'Hardware Solutions Ltd',
    contactPerson: 'David Wilson',
    email: 'david@hardwaresol.com',
    phone: '+91-8765432107',
    gstTin: 'GSTIN777888999',
    paymentTerms: 30,
  },
];

export const generateSampleSaleOrders = (customers: any[]) => {
  if (customers.length === 0) return [];

  return [
    {
      customerId: customers[0]?.id,
      customerName: customers[0]?.name || 'Tech Solutions Inc',
      soDate: new Date('2025-01-15'),
      poNumber: 'PO-2025-001',
      poDate: new Date('2025-01-10'),
      lineItems: [
        {
          id: 'so-item-1',
          particulars: 'Software Development Services - Custom CRM Module',
          soQty: 1,
          qtyDispatched: 0,
          balanceQty: 1,
          basicAmount: 150000,
          gstPercent: 18,
          gstAmount: 27000,
          lineTotal: 177000,
        },
        {
          id: 'so-item-2',
          particulars: 'Database Setup and Configuration - PostgreSQL',
          soQty: 1,
          qtyDispatched: 0,
          balanceQty: 1,
          basicAmount: 50000,
          gstPercent: 18,
          gstAmount: 9000,
          lineTotal: 59000,
        },
      ],
      total: 236000,
      status: 'Confirmed' as const,
      notes: 'Project to be completed in 3 months',
    },
    {
      customerId: customers[1]?.id,
      customerName: customers[1]?.name || 'Global Enterprises Ltd',
      soDate: new Date('2025-01-18'),
      poNumber: 'PO-2025-002',
      poDate: new Date('2025-01-15'),
      lineItems: [
        {
          id: 'so-item-3',
          particulars: 'Cloud Infrastructure Setup - AWS',
          soQty: 1,
          qtyDispatched: 1,
          balanceQty: 0,
          basicAmount: 200000,
          gstPercent: 18,
          gstAmount: 36000,
          lineTotal: 236000,
        },
        {
          id: 'so-item-4',
          particulars: 'Security Audit Services',
          soQty: 1,
          qtyDispatched: 0,
          balanceQty: 1,
          basicAmount: 75000,
          gstPercent: 18,
          gstAmount: 13500,
          lineTotal: 88500,
        },
        {
          id: 'so-item-5',
          particulars: 'DevOps Implementation - CI/CD Pipeline',
          soQty: 1,
          qtyDispatched: 0,
          balanceQty: 1,
          basicAmount: 100000,
          gstPercent: 18,
          gstAmount: 18000,
          lineTotal: 118000,
        },
      ],
      total: 442500,
      status: 'Dispatched' as const,
      notes: 'Priority project - Phase 1 completed',
    },
    {
      customerId: customers[2]?.id,
      customerName: customers[2]?.name || 'Innovative Systems Pvt Ltd',
      soDate: new Date('2025-01-20'),
      poNumber: 'PO-2025-003',
      lineItems: [
        {
          id: 'so-item-6',
          particulars: 'Mobile App Development - iOS & Android',
          soQty: 1,
          qtyDispatched: 0,
          balanceQty: 1,
          basicAmount: 300000,
          gstPercent: 18,
          gstAmount: 54000,
          lineTotal: 354000,
        },
        {
          id: 'so-item-7',
          particulars: 'UI/UX Design Services',
          soQty: 1,
          qtyDispatched: 0,
          balanceQty: 1,
          basicAmount: 80000,
          gstPercent: 18,
          gstAmount: 14400,
          lineTotal: 94400,
        },
      ],
      total: 448400,
      status: 'Draft' as const,
      notes: 'Waiting for client approval on design mockups',
    },
    {
      customerId: customers[3]?.id || customers[0]?.id,
      customerName: customers[3]?.name || customers[0]?.name || 'Digital Marketing Agency',
      soDate: new Date('2025-01-22'),
      poNumber: 'PO-2025-004',
      poDate: new Date('2025-01-20'),
      lineItems: [
        {
          id: 'so-item-8',
          particulars: 'SEO Optimization Services',
          soQty: 1,
          qtyDispatched: 1,
          balanceQty: 0,
          basicAmount: 60000,
          gstPercent: 18,
          gstAmount: 10800,
          lineTotal: 70800,
        },
        {
          id: 'so-item-9',
          particulars: 'Content Marketing Campaign',
          soQty: 1,
          qtyDispatched: 1,
          balanceQty: 0,
          basicAmount: 90000,
          gstPercent: 18,
          gstAmount: 16200,
          lineTotal: 106200,
        },
      ],
      total: 177000,
      status: 'Delivered' as const,
      notes: 'Campaign completed successfully',
    },
  ];
};

export const generateSampleInvoices = (vendors: any[]) => {
  if (vendors.length === 0) return [];

  const dueDate1 = new Date();
  dueDate1.setDate(dueDate1.getDate() + 30);

  const dueDate2 = new Date();
  dueDate2.setDate(dueDate2.getDate() - 5); // Overdue

  const dueDate3 = new Date();
  dueDate3.setDate(dueDate3.getDate() + 15);

  return [
    {
      invoiceDate: new Date('2025-01-10'),
      vendorId: vendors[0]?.id,
      vendorName: vendors[0]?.name || 'CloudTech Suppliers',
      poNumber: 'PO-V-2025-001',
      poDate: new Date('2025-01-05'),
      lineItems: [
        {
          id: 'inv-item-1',
          particulars: 'Cloud Server Rental - AWS EC2 Instances',
          qtyDispatched: 12,
          basicAmount: 120000,
          gstAmount: 21600,
          lineTotal: 141600,
        },
        {
          id: 'inv-item-2',
          particulars: 'Data Storage - S3 Buckets',
          qtyDispatched: 1,
          basicAmount: 30000,
          gstAmount: 5400,
          lineTotal: 35400,
        },
      ],
      gstPercent: 18,
      transportationCost: 5000,
      discount: 2000,
      totalCost: 180000,
      amountReceived: 180000,
      pendingAmount: 0,
      status: 'Paid' as const,
      dueDate: dueDate1,
    },
    {
      invoiceDate: new Date('2025-01-08'),
      vendorId: vendors[1]?.id,
      vendorName: vendors[1]?.name || 'Software Services Inc',
      poNumber: 'PO-V-2025-002',
      poDate: new Date('2025-01-03'),
      lineItems: [
        {
          id: 'inv-item-3',
          particulars: 'Software License - Enterprise Edition',
          qtyDispatched: 50,
          basicAmount: 250000,
          gstAmount: 45000,
          lineTotal: 295000,
        },
      ],
      gstPercent: 18,
      transportationCost: 0,
      discount: 5000,
      totalCost: 290000,
      amountReceived: 100000,
      pendingAmount: 190000,
      status: 'Overdue' as const,
      dueDate: dueDate2,
    },
    {
      invoiceDate: new Date('2025-01-18'),
      vendorId: vendors[2]?.id,
      vendorName: vendors[2]?.name || 'Hardware Solutions Ltd',
      poNumber: 'PO-V-2025-003',
      poDate: new Date('2025-01-15'),
      lineItems: [
        {
          id: 'inv-item-4',
          particulars: 'Workstation Computers - Dell OptiPlex',
          qtyDispatched: 10,
          basicAmount: 500000,
          gstAmount: 90000,
          lineTotal: 590000,
        },
        {
          id: 'inv-item-5',
          particulars: 'Monitors - 27 inch LED',
          qtyDispatched: 20,
          basicAmount: 100000,
          gstAmount: 18000,
          lineTotal: 118000,
        },
        {
          id: 'inv-item-6',
          particulars: 'Networking Equipment - Switches & Routers',
          qtyDispatched: 5,
          basicAmount: 150000,
          gstAmount: 27000,
          lineTotal: 177000,
        },
      ],
      gstPercent: 18,
      transportationCost: 15000,
      discount: 10000,
      totalCost: 890000,
      amountReceived: 0,
      pendingAmount: 890000,
      status: 'Unpaid' as const,
      dueDate: dueDate3,
    },
  ];
};

export const sampleExpenses = [
  {
    date: new Date('2025-01-15'),
    category: 'Travel' as const,
    description: 'Client meeting in Mumbai - Flight tickets and hotel',
    amount: 25000,
    paymentMode: 'Card' as const,
    status: 'Paid' as const,
  },
  {
    date: new Date('2025-01-10'),
    category: 'Rent' as const,
    description: 'Office rent for January 2025',
    amount: 80000,
    paymentMode: 'Bank Transfer' as const,
    status: 'Paid' as const,
  },
  {
    date: new Date('2025-01-12'),
    category: 'Utilities' as const,
    description: 'Electricity and water bill',
    amount: 12000,
    paymentMode: 'UPI' as const,
    status: 'Paid' as const,
  },
  {
    date: new Date('2025-01-18'),
    category: 'Supplies' as const,
    description: 'Office supplies - stationery and pantry items',
    amount: 8500,
    paymentMode: 'Cash' as const,
    status: 'Paid' as const,
  },
  {
    date: new Date('2025-01-20'),
    category: 'Misc' as const,
    description: 'Team building event and lunch',
    amount: 15000,
    paymentMode: 'Card' as const,
    status: 'Paid' as const,
  },
  {
    date: new Date('2025-01-22'),
    category: 'Travel' as const,
    description: 'Local transportation - Cab charges',
    amount: 3500,
    paymentMode: 'UPI' as const,
    status: 'Paid' as const,
  },
  {
    date: new Date('2025-01-25'),
    category: 'Utilities' as const,
    description: 'Internet and phone bills',
    amount: 6000,
    paymentMode: 'Bank Transfer' as const,
    status: 'Pending' as const,
  },
];
