// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbiaegfropzzndjnfhoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iaWFlZ2Zyb3B6em5kam5maG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMzI2NDAsImV4cCI6MjA3NjcwODY0MH0.HS3ejjbt1dnU9EslRhjTUr3FpbBkmk5qWL_BCp_N_ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});